### ISSUE TITLE
calculate

### ISSUE THREAD

**Issue by ZJ-Zhang-0906** [lfnovo/open-notebook#23]
Can he calculate financial indicators?

**Comment by lfnovo** [comment]
Hi @ZJ-Zhang-0906  if you mean whether the model can be instructed to extract and calculate indicators, most likely yes. You should play with the transformations in order to achieve a prompt that helps you with that.

**Comment by ZJ-Zhang-0906** [comment]
Is it okay if I want him to calculate certain financial indicators?

**Comment by lfnovo** [comment]
Yes, just try it out as a Transformation and let me know if that works for you. I recommend using claude-3-5-sonnet-latest as your model for that.

**Comment by ZJ-Zhang-0906** [comment]
Does it have an API I can use?

**Comment by lfnovo** [comment]
Not at this point.. you are probably looking for a tool like: https://github.com/danielmiessler/fabric
