### ISSUE TITLE
Installing from Source - SURREAL_ADDRESS

### ISSUE THREAD

**Issue by seonake** [lfnovo/open-notebook#24]
Hi, i just followed "installing from source" steps and i got:
File "H:\Notebook\open_notebook\open_notebook\database\repository.py", line 12, in db_connection
    host=os.environ["SURREAL_ADDRESS"],
         ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
File "<frozen os>", line 679, in __getitem__

Maybe i have to change something in .env file?
Thanks in advance.

**Comment by lfnovo** [comment]
Can you post your .env file here (just mask the keys)?

Or at least confirm it's like this: 

SURREAL_ADDRESS="localhost"
SURREAL_PORT=8000
SURREAL_USER="root"
SURREAL_PASS="root"
SURREAL_NAMESPACE="open_notebook"
SURREAL_DATABASE="open_notebook"

Also, how are you starting the app?

**Comment by seonake** [comment]
Hi, thanks for the answer.

My .env file looks the same to me:
SURREAL_ADDRESS="localhost"
SURREAL_PORT=8000
SURREAL_USER="root"
SURREAL_PASS="root"
SURREAL_NAMESPACE="open_notebook"
SURREAL_DATABASE="open_notebook"

My commands:
-  docker compose --profile db_only up -d  [to start the database]
- poetry run streamlit run app_home.py  [to start the app]

**Comment by lfnovo** [comment]
Humm.. I have a guess - try installing: https://pypi.org/project/poetry-dotenv/
I am relying on this guy to manage env.. probably should move to dotenv though

**Comment by seonake** [comment]
yes, this fixed it: pip install poetry-dotenv
Thanks a lot

**Comment by seonake** [comment]
yes, this fixed it: pip install poetry-dotenv
Thanks a lot

**Comment by seonake** [comment]
This is needed too:
pip install python-magic-bin
